"""Stable application and protocol constants."""

API_V1_PREFIX = "/api/v1"
PROTOCOL_VERSION = "llmbenchlab-protocol-v1"
DEFAULT_CONNECT_TIMEOUT_SECONDS = 5.0
DEFAULT_READ_TIMEOUT_SECONDS = 60.0
DEFAULT_WRITE_TIMEOUT_SECONDS = 30.0
DEFAULT_POOL_TIMEOUT_SECONDS = 5.0
MAX_GENERATION_TOKENS = 131_072
MIN_READ_TIMEOUT_SECONDS = 1.0
MAX_READ_TIMEOUT_SECONDS = 1_800.0
DEFAULT_MAX_RETRIES = 2
DEFAULT_RETRY_BACKOFF_BASE_SECONDS = 0.25
DEFAULT_RETRY_BACKOFF_CAP_SECONDS = 2.0
RETRYABLE_PROVIDER_STATUS_CODES = (408, 429, 500, 502, 503, 504)
